services:
  - type: web
    name: automl-lite-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn -w 1 -k gthread -b 0.0.0.0:$PORT app:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 2

  - type: static
    name: automl-lite-frontend
    buildCommand: cd frontend && npm ci && npm run build
    publishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE
        fromService:
          type: web
          name: automl-lite-backend
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html


